id: I814E11F4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T18:00:24+00:00'
last_modified: '2022-06-07T14:13:34.337268+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB16631
  title: གསུང་འབུམ། མི་ཕམ་རྒྱ་མཚོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A58C:
      image_group_id: I1PD34647
      title: ''
      total_pages: 694
      order: 1
      base_file: A58C.txt
    E8F4:
      image_group_id: I1PD34648
      title: ''
      total_pages: 702
      order: 2
      base_file: E8F4.txt
    '5551':
      image_group_id: I1PD34649
      title: ''
      total_pages: 928
      order: 3
      base_file: 5551.txt
    '2851':
      image_group_id: I1PD34650
      title: ''
      total_pages: 774
      order: 4
      base_file: 2851.txt
    3F07:
      image_group_id: I1PD34651
      title: ''
      total_pages: 294
      order: 5
      base_file: 3F07.txt
    C5C4:
      image_group_id: I1PD34652
      title: ''
      total_pages: 1206
      order: 6
      base_file: C5C4.txt
    F845:
      image_group_id: I1PD34653
      title: ''
      total_pages: 254
      order: 7
      base_file: F845.txt
    '3030':
      image_group_id: I1PD34654
      title: ''
      total_pages: 1054
      order: 8
      base_file: 3030.txt
    C48D:
      image_group_id: I1PD34655
      title: ''
      total_pages: 652
      order: 9
      base_file: C48D.txt
    8B5B:
      image_group_id: I1PD34656
      title: ''
      total_pages: 302
      order: 10
      base_file: 8B5B.txt
    E6DE:
      image_group_id: I1PD34657
      title: ''
      total_pages: 740
      order: 11
      base_file: E6DE.txt
    8B28:
      image_group_id: I1PD34658
      title: ''
      total_pages: 458
      order: 12
      base_file: 8B28.txt
    411F:
      image_group_id: I1PD34659
      title: ''
      total_pages: 812
      order: 13
      base_file: 411F.txt
    4AC8:
      image_group_id: I1PD34660
      title: ''
      total_pages: 668
      order: 14
      base_file: 4AC8.txt
    F9A7:
      image_group_id: I1PD34661
      title: ''
      total_pages: 430
      order: 15
      base_file: F9A7.txt
    4C6E:
      image_group_id: I1PD34662
      title: ''
      total_pages: 840
      order: 16
      base_file: 4C6E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
